---
title: "Some Pregame Plots"
author: "Michael Mullarkey"
date: "7/20/2021"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
require("knitr")
## setting working directory
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, warning = FALSE, message = FALSE, include = FALSE)
```

```{r}

library(extrafont)
fonts()

library(showtext)

font_add_google(name = "Rakkas",   # Name of the font on the Google Fonts site
                family = "rakkas") # Name you want to use to call the font

font_add_google(name = "Concert One",   # Name of the font on the Google Fonts site
                family = "concert") # Name you want to use to call the font

font_add_google(name = "Playfair Display",   # Name of the font on the Google Fonts site
                family = "playfair") # Name you want to use to call the font


```


```{r}

library(tidyverse)

d <- read_csv("train.csv") %>% 
  mutate(across(
    where(is.character),
    as.factor
  ))

```

```{r}
library(skimr)

skim(d)

```

```{r}

glimpse(d)

```
```{r}

showtext_auto()

d %>% 
  ggplot(aes(customer_age, total_trans_amt, color = gender)) + 
  geom_jitter(alpha = 0.2) +
  scale_color_viridis_d() +
  theme_minimal() +
  theme(text = element_text(family = "rakkas")) +
  labs(x = "Credit Limit", y = "Total Transaction Amount", color = "Biological Sex",
       title = "Credit Limit Not That Related to Total Transaction Amount",
       subtitle = "At Least If We Look at a Linear Relationship") +
  geom_smooth(method = "lm", formula = "y ~ x")
  

```
```{r}

d %>% 
  ggplot(aes(customer_age, total_trans_amt, color = gender)) + 
  geom_jitter(alpha = 0.2) +
  scale_color_viridis_d() +
  theme_minimal() +
  theme(text = element_text(family = "concert")) +
  labs(x = "Credit Limit", y = "Total Transaction Amount", color = "Biological Sex",
       title = "A Non-Linear Model Demands We Accept Negative Transcation Amounts",
       subtitle = "At Least It's Not a Map") +
  geom_smooth(method = "gam")

```
```{r}

library(ggridges)
library(wesanderson)

d %>% 
  mutate(gender = factor(case_when(
    
    gender == "F" ~ "Female",
    gender == "M" ~ "Male",
    TRUE ~ NA_character_
    
  ))) %>% 
  ggplot(aes(credit_limit, gender, fill = gender, color = gender)) +
  geom_density_ridges(alpha = 0.25, jittered_points = TRUE, position = "raincloud") +
  scale_fill_viridis_d(option = "turbo") +
  scale_color_viridis_d(option = "turbo") +
  theme_minimal() +
  theme(text = element_text(family = "concert")) +
  theme(legend.position = "none") +
  labs(x = "Credit Limit", y = "Biological Sex",
       title = "Wow, Lots of Dudes Have 'Top Level' Credit Limits",
       subtitle = "I'm Sure That's Just a Coincidence...") +
  annotate("text", x = 21000, y = 2.5, label = "There are also fewer dudes at the low end of credit limit",
           family = "concert") +
  annotate("rect", xmin = 0, xmax = 7000, ymin = 1, ymax = 3, alpha = 0.2)

```
```{r}

library(ggalluvial)

glimpse(d)

skim(d)

d %>% 
   count(income_category)
 
d %>% 
   count(education_level)

d %>% 
  filter(income_category != "Unknown" & education_level != "Unknown") %>% 
  mutate(education_level = as.character(education_level),
    education_level = factor(case_when(
    
    education_level == "Uneducated" ~ "< High School",
    TRUE ~ education_level
    
  ))) %>% 
  group_by(income_category, education_level) %>% 
  summarise(freq = n()) %>% 
  mutate(
         education_level = fct_relevel(education_level, "Doctorate", "Post-Graduate", "Graduate", "College",
                                       "High School","Uneducated"),
         income_category = fct_relevel(income_category, "$120K +", "$80K - $120K", "$60K - $80K",
                                       "$40K - $60K", "Less than $40K")) %>% 
  ggplot(aes(axis1 = education_level, axis2 = income_category, y = freq)) +
  geom_alluvium(aes(fill = education_level)) + 
  scale_x_discrete(limits = c("Education Level", "Income Bracket"), expand = c(.05, .05)) +
  geom_stratum(width = 1/8, fill = "black", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum)), family = "concert") +
  labs(y = "# of People", fill = "Education",
       title = "How Does Education Level Relate to Income Level in SLICED EP 07 Data?",
       subtitle = "People Seem Almost Suspiciously Upwardly Mobile (Good for them! And also...)") +
  scale_fill_viridis_d(option = "rocket") +
  theme_dark() +
  theme(text = element_text(family = "concert"),
        axis.text.x = element_text(size = 13),
        plot.title = element_text(size = 15),
        axis.title.y = element_text(size = 14),
        legend.position = "none",
        plot.background = element_rect("gray"))

```

```{r}

test <- d %>% 
  group_by(income_category, education_level) %>% 
  summarise(freq = n()) %>% 
  mutate(
         education_level = fct_relevel(education_level, "Doctorate", "Post-Graduate", "Graduate", "College",
                                       "High School","Uneducated", "Unknown"),
         income_category = fct_relevel(income_category, "$120K +", "$80K - $120K", "$60K - $80K",
                                       "$40K - $60K", "Less than $40K", "Unknown"))

test %>% 
  count(income_category)

levels(test$income_category)

education_level = case_when(
    education_level == "Post-Graduate" ~ factor("Post-Grad"),
    education_level == "Uneducated" ~ factor("< High School"),
    TRUE ~ education_level
  ),

```

